### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp (Java 17) and de.invesdwin:invesdwin-instrument:1.0.14 or de.invesdwin:invesdwin-instrument:1.0.10

### ISSUE THREAD

**Issue by rsurendar** [invesdwin/invesdwin-instrument#26] opened 2023-02-07 13:06 UTC
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.test.Application.main(Application.java:17)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp
	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:111)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:90)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp
	at de.invesdwin.instrument.DynamicInstrumentationLoader.setAgentClassLoaderReference(DynamicInstrumentationLoader.java:157)
	at de.invesdwin.instrument.DynamicInstrumentationLoader.<clinit>(DynamicInstrumentationLoader.java:80)
	... 1 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp

Caused by: java.lang.NoSuchFieldException: ucp
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
Caused by: java.lang.NoSuchFieldException: ucp
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addUrlToAppClassLoaderURLClassPath(DynamicInstrumentationReflections.java:114)
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addPathToSystemClassLoader(DynamicInstrumentationReflections.java:75)
	... 3 more
```

**Comment by rsurendar** [comment] 2023-02-07 13:14
spring-boot 2.7.7
		maven {
			url "https://invesdwin.de/repo/invesdwin-oss-remote"
			allowInsecureProtocol true
		}
add the below property in gradle.properties
-add-opens=java.base/jdk.internal.loader=ALL-UNNAMED \

**Comment by subes** [comment] 2023-02-07 15:13
Can you debug and check that the classloader that is provided into the method is actually a `jdk.internal.loader.ClassLoaders.AppClassLoader` or a different type? Maybe gradle or something else prevents the root class loader from being loaded? Or did your specific Java 17 version change the `ucp` field in the `AppClassLoader` and we have to update the reflection?

**Comment by rsurendar** [comment] 2023-02-07 19:22
@Deprecated(since="17", forRemoval=true)
    public static SecurityManager getSecurityManager() {
        if (allowSecurityManager()) {
            return security;
        } else {
            return null;
        }
    }

**Comment by subes** [comment] 2023-02-08 15:01
I don't understand how your comment about the security manager answers any question or provides relevant information.

**Comment by subes** [comment] 2023-02-08 19:07
Also interesting would be to know what JVM you are running. If it deviates from OpenJDK too much, some adjustments might be required. Or if it is OpenJDK 17, which patch level? I can not reproduce with the  latest OpenJDK versions I have available in Ubuntu or Manjaro.

**Comment by rsurendar** [comment] 2023-02-08 19:11
1Q) check that the classloader that is provided into the method is actually a jdk.internal.loader.ClassLoaders.AppClassLoader?
Yes, its  jdk.internal.loader.ClassLoaders.AppClassLoader.

My JVM running on Adoptium OpenJdk 17.0.4.101

In  JDK 11

  ##https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/19fb8f93c59dfd791f62d41f332db9e306bc1422/src/java.base/share/classes/jdk/internal/loader/ClassLoaders.java#L161

There is a ucp filed in Appclassloader Class; below is the core snippet from the above jdk 11 source URL.
/**
     * The application class loader that is a {@code BuiltinClassLoader} with
     * customizations to be compatible with long standing behavior.
     */
    private static class AppClassLoader extends BuiltinClassLoader {
        static {
            if (!ClassLoader.registerAsParallelCapable())
                throw new InternalError();
        }

        final URLClassPath ucp;

        AppClassLoader(PlatformClassLoader parent, URLClassPath ucp) {
            super("app", parent, ucp);
            this.ucp = ucp;
        }
==================================================================================
- Open Jdk 17.0.4.101 
https://github.com/openjdk/jdk/blob/b575dd80b6e86821fcf3e065e31c6bddb85db6c4/src/java.base/share/classes/jdk/internal/loader/ClassLoaders.java#L165

There is a ucp filed in Appclassloader Class; below is the core snippet from the above jdk 17 source URL.
- private static class AppClassLoader extends BuiltinClassLoader {
        static {
            if (!ClassLoader.registerAsParallelCapable())
                throw new InternalError();
        }

        AppClassLoader(BuiltinClassLoader parent, URLClassPath ucp) {
            super("app", parent, ucp);
        }
        
        @Override
        protected Class<?> loadClass(String cn, boolean resolve)
            throws ClassNotFoundException
        {
            // for compatibility reasons, say where restricted package list has
            // been updated to list API packages in the unnamed module.
            SecurityManager sm = System.getSecurityManager();
            if (sm != null) {
                int i = cn.lastIndexOf('.');
                if (i != -1) {
                    sm.checkPackageAccess(cn.substring(0, i));
                }
            }

            return super.loadClass(cn, resolve);
        }

**Comment by subes** [comment] 2023-02-12 08:40
I am running this OpenJDK without an issue:
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10)
OpenJDK 64-Bit Server VM (build 17.0.6+10, mixed mode)

What version of invesdwin-instrument are you running?

This is a duplicate of https://github.com/invesdwin/invesdwin-instrument/issues/19 and https://github.com/invesdwin/invesdwin-instrument/issues/22. It was fixed with this commit: https://github.com/invesdwin/invesdwin-instrument/commit/7d639c2c934d1a8ce206ec915e8c321c344529d3

Please update invesdwin-instrument to version 1.0.14.

**Closed as completed by subes** 2023-02-12 08:40 UTC

**Comment by rsurendar** [comment] 2023-02-13 18:11
What version of invesdwin-instrument are you running?
- We are invesdwin-instrument version **1.0.14**.


-I am running this **OpenJDK 17.0.4.101**
-link: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.4.1%2B1

spring-boot 2.7.7
maven {
url "https://invesdwin.de/repo/invesdwin-oss-remote"
allowInsecureProtocol true
}
add the below property in gradle.properties
-add-opens=java.base/jdk.internal.loader=ALL-UNNAMED \

Same issue: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: ucp.
Let me know if I need to include anything.

**Comment by subes** [comment] 2023-02-13 20:05
This is not possible.

The stacktrace you provided matches an earlier version before the mentioned commit that fixes this issue:
```
Caused by: java.lang.NoSuchFieldException: ucp
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
Caused by: java.lang.NoSuchFieldException: ucp
	at de.invesdwin.instrument.DynamicInstrumentationReflections.addUrlToAppClassLoaderURLClassPath(DynamicInstrumentationReflections.java:114)
```

The new code calls getField in line 130 (not 114) which calls Class.getDeclaredField in line 111 (looking into the parent/super class where the ucp field exists).
See screenshot:
![image](https://user-images.githubusercontent.com/332937/218563014-7ac4b638-c3ba-4b88-9e4a-e1d35b1cfc41.png)

Are you sure you don't have duplicate classes/jars in the classpath? Can you open your `DynamicInstrumentationReflections.class` in a decompiler (jd-gui for example) and verify you have the correct implementation?

**Comment by subes** [comment] 2023-02-13 20:05
If you don't find an issue, please provide a sample project with which I can reproduce the error.

**Comment by rsurendar** [comment] 2023-02-13 21:59
I will verify and get back to you.
