### ISSUE TITLE
Error when running with a standalone jar

### ISSUE THREAD

**Issue by crosslover** [invesdwin/invesdwin-instrument#3] opened 2017-09-07 10:05 UTC
as the title says, Error happens:

Exception in thread "Attach Listener" java.lang.ClassFormatError: Incompatible magic value 1347093252 in class file com/xiaoju/uemc/wheeljack/instrument/internal/DynamicInstrumentationAgent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:407)
Agent failed to start!
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.xiaoju.uemc.wheeljack.instrument.DynamicInstrumentationLoader$1.run(DynamicInstrumentationLoader.java:76)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.xiaoju.uemc.wheeljack.instrument.DynamicInstrumentationLoader$1.run(DynamicInstrumentationLoader.java:73)
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
	at com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:526)
	... 5 more

It's probably because of the temporary jar file generated by the code is a zip, so the magic number is not correct for a java class.

**Comment by subes** [comment] 2017-09-15 21:00
Hmm, never encountered this problem. Since the package name is different, you seem to use some funny way of creating a standalone jar. Can you provide a sample to reproduce the issue?

Otherwise here is an example project how I create my standalone jars via maven-shade-plugin: [granatasoft-remotelist-website-dist](https://github.com/subes/invesdwin-nowicket/blob/master/invesdwin-nowicket-parent/invesdwin-nowicket-examples/granatasoft-remotelist-parent/granatasoft-remotelist-website-dist/pom.xml)

And here is the parent pom defining the maven-shade-plugin settings that are reused in the above example (starting at line 751):
[invesdwin-context-parent](https://github.com/subes/invesdwin-context/blob/master/invesdwin-context-parent/pom.xml#L751)

Hope this helps.

**Comment by crosslover** [comment] 2017-09-18 07:12
OK...The issue above is caused by the fact that when I run as a standalone jar the whole jar is writen to the tmp path as the agent jar. I adjusted the code in the 'getAgentClassInputStream' method, it was solved.
However it is still not done, because what i am using is the default spring boot package plugin, which will cause all users' business code will be loaded by the spring boot's 'LaunchedURLClassLoader' while the 'com.sun.tools.attach.VirtualMachine.loadAgent' is using default system class loader......so something tricky will be needed...
thx anyway!

**Comment by subes** [comment] 2017-09-18 09:50
Ok, I was not aware of the whole jar being included (meaning all classes). I expected only the DynamicInstrumentationAgent.class to be written as a jar into the tmp path. Can you provide a pull request or code snippet for the fix so I can put it in this repo?

**Comment by subes** [comment] 2017-09-18 21:23
Nevermind, fixed the code myself. If you find out anything about the classloader issue tell me. Or maybe you want to provide a sample project for it so I can have a look at it.

Here is the way I do the standalone jar with spring-boot (without additional classloaders): [invesdwin-nowicket-examples-guide starting at line 232](https://github.com/subes/invesdwin-nowicket/blob/master/invesdwin-nowicket-parent/invesdwin-nowicket-examples/invesdwin-nowicket-examples-guide/pom.xml#L232)

Notice the: `<transformers combine.self="override">`

**Comment by crosslover** [comment] 2017-09-19 12:32
Sure, just thought that a version for the default spring boot package plugin would be very nice for your contribution.
Below is a sniplet in the manifest.mf generated by the spring boot package plugin:

```
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: com.xxx.uemc.wheeljack.Application
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
```

and the related source code is below which used `		Thread.currentThread().setContextClassLoader(classLoader);
`
, maybe you would be interested:
[https://github.com/spring-projects/spring-boot/tree/6eaa8d7c56fb98ac419486bd153943b0c1de29c4/spring-boot-tools/spring-boot-loader/src/main/java/org/springframework/boot/loader](url)

**Comment by subes** [comment] 2017-09-19 17:03
This issue might be fixed in spring-boot 1.4 already: https://github.com/spring-projects/spring-boot/issues/4868

Can you verify?

Also a sample project would still be helpful so I can reproduce the issue. Or you could at least provide the current exception stacktrace you get. Looking at the LaunchedURLClassLoader there might be a simple solution to this depending on the actual error message. Maybe remembering the classloader to use as a static variable and letting the agent class proceed from that classloader could solve the issue.

**Comment by subes** [comment] 2017-09-19 17:12
For leaking the LaunchedURLClassLoader instance to the DynamicInstrumentationAgent we might need to define a class with a static variable, load it into the SystemClassLoader, set the static variable in it via reflection and access the defined class and variable again via reflection in the agent. This workaround is needed because the SystemClassLoader will not be aware of any classes loaded by spring-boot. Adding classpath entries to the SystemClassLoader is already demonstrated in invesdwin-instrument by adding the tools.jar automagically.

**Comment by subes** [comment] 2017-09-19 20:56
Ok, I found out the bug in spring-boot I referenced two posts ago had an example project to reproduce the issue. I was able to test my workaround and pushed a fix for this issue. Also I have included my testcase here: https://github.com/subes/invesdwin-instrument/tree/master/tests/springboot-instrumentation-testapp

Please check if the current version of invesdwin-instrument works for you. :)

**Comment by crosslover** [comment] 2017-09-22 09:08
Sure, thank you for the work, I'll see the commit.

**Comment by crosslover** [comment] 2017-09-26 08:13
Great work, that works for me and the code is quite enlightening for me.
This will be helpful for these low-level spring boot users.

**Comment by subes** [comment] 2017-09-26 11:28
Great, thanks for the bug report and helping to resolve it. Closing it now.

**Closed as completed by subes** 2017-09-26 11:28 UTC
