### ISSUE TITLE
AspectJ Weaver doesn't load all spring components when spring-boot-devtools is activated

### ISSUE THREAD

**Issue by sayseakleng** [invesdwin/invesdwin-instrument#24] opened 2021-08-15 03:15 UTC
Hello friends!

I'm facing an issue that AspectJ Weaver doesn't load all components when spring-boot-devtools lib is activated

**1. When spring-boot-devtools is removed**

![image](https://user-images.githubusercontent.com/19582007/129465564-74d8bc82-1b6b-48be-947d-9c7fba0eb9c7.png)

![image](https://user-images.githubusercontent.com/19582007/129465628-322b32f1-796a-4a07-9cac-6766d32d207d.png)
==> @Async & @Cacheable components and (@Service @Transactional)  combination were weaved correctly

**2. When spring-boot-devtools is activated**

![image](https://user-images.githubusercontent.com/19582007/129465748-55ab5e4e-27f0-4ca3-bda9-501ac76ed014.png)

==> AspectJ Weaver weaved only components with @Repository
==>  AspectJ Weaver doesn't weave  @Async @Cacheable components and all service classes with (@Service @Transactional) combination.

Here is my environment:
JDK: 1.8
Lombok: 1.18.12
Spring Boot: 2.3.12
aspectjweaver: 1.9.7
invesdwin-instrument: 1.0.14

Regards.

**Comment by subes** [comment] 2021-08-15 09:25
Do you have a sample project that reproduces the problem? I need something to debug to find out what is happening.
By my guess is that spring-boot-devtools loads most classes before invesdwin-instrument is initialized (which then can not be woven anymore). You see that Spring modified the classes with the "$$EnhancerBySpringCGLIB..." suffix. Only because these are new classes which get loaded (afterwards), they get then also woven anew by spring-aspects. All other classes that got loaded before instrumentation got initialized are not woven since aspectj (or more specifically instrumentation via the agent) was not setup at that time.

Also I guess this did not work for prior versions of invesdwin-instrument as well due to spring-boot-devtools changing the order of loading classes. Also the recent changes in invesdwin-instrument could not cause a regression like this.

Specifically these infos are missing for me:
- Where is invesdwin-instrument initialized: statically in a main class before any spring-boot magic happens?
- Do you launch from IDE (with some spring plugins) or a packaged jar?
- Does Spring-Boot (or Spring-Boot-DevTools) add an intermediary classloader or scans (+loads) the classes before instrumentation takes place?
- Does it work when using the -javaagent jvm param with Spring-Boot-DevTools?

Maybe you can create a minimal reproducing sample like this: https://github.com/invesdwin/invesdwin-instrument/tree/master/tests/springboot-instrumentation-testapp

**Comment by sayseakleng** [comment] 2021-08-16 15:28
Hello @subes ! Here is the example: https://drive.google.com/drive/folders/17sVNKn0mNMuULJTmxaUt6dPssi2oO_DO?usp=sharing.

 **developmentOnly 'org.springframework.boot:spring-boot-devtools'**

You can comment this out to make Load Time Weaver works when you run sample form com.sample.api.server.Application.

**Comment by subes** [comment] 2021-10-04 16:33
Hi, thanks for the sample. 

I see spring-boot-devtools uses a `org.springframework.boot.devtools.restart.RestartLauncher` to relaunch the application.
I extended your sample here: https://github.com/invesdwin/invesdwin-instrument/tree/master/tests/springboot-devtools-testapp
to use AspectJ and test that an example aspect works fine. This works both with and without devtools since invesdwin-instrument handles nested classloaders and reinitializations well. Thus the `InstrumentationSavingAgent.getInstrumentation()` always holds a valid instrumentation provider. 

Note that with AspectJ-LTW one has to provide an META-INF/aop.xml to enable the aspects during load time weaving. Note the `-Xreweavable` which allows the nested classloader to reinitialize aspectj.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectj PUBLIC "-//AspectJ//DTD//EN" "http://www.eclipse.org/aspectj/dtd/aspectj.dtd">
<aspectj>
	<weaver
		options="-Xset:weaveJavaxPackages=true -verbose -showWeaveInfo -Xreweavable">
		<include within="com.sample.api.server.core.service.impl.*" />
		<include within="com.sample.api.server.test.*" />
	</weaver>
	<aspects>
		<aspect name="com.sample.api.server.test.TestAspect" />
	</aspects>
</aspectj>
```
Also with spring-boot-devtools one has to explicitly invoke the AspectJ agent within the nested classloader:
`org.aspectj.weaver.loadtime.Agent.agentmain("", InstrumentationSavingAgent.getInstrumentation());`

Another problem you encounter is that lombok does not use AspectJ, instead it seems to be a compiler plugin of some sort that hooks into IDEs (some might require plugins) and maven/gradle compilations. Though it also provides a java agent that might work with invesdwin-instrument. Full example here: https://github.com/invesdwin/invesdwin-instrument/blob/master/tests/springboot-devtools-testapp/src/main/java/com/sample/api/server/Application.java

```
		/*
		 * try to load lombok
		 */
		final Class<?> lombokAgentClass = Class.forName("lombok.launch.Agent");
		final Method agentMainMethod = lombokAgentClass.getDeclaredMethod("agentmain", String.class,
				Instrumentation.class);
		// java 16 workaround
		StaticComponentContainer.Methods.setAccessible(agentMainMethod, true);
		agentMainMethod.invoke(null, "", InstrumentationSavingAgent.getInstrumentation());
		/*
		 * causes java 16 module errors inside
		 * org.springframework.boot.devtools.restart.RestartLauncher
		 * 
		 */
//		AgentAccessor.agentmain("", InstrumentationSavingAgent.getInstrumentation());
```

Lombok gets initialized before the class is loaded, so it should be applied properly, but somehow the code that should be generated by Lombok does not get generated. Maybe I saw some ghosts, but I had the impression that I had one run where the classes got generated, but I can not reproduce it or the code that made it work supposedly.
I think this is a lombok internal issue that it does not work with nested classloaders (as used by org.springframework.boot.devtools.restart.RestartLauncher).
An idea would be to debug into the hooks inside lombok that should modify the class and see if it actually gets triggered.
Though I found no way to do this because I can only see .lombok files in the lombok jar. So dunno how one is supposed to debug that thing... It might also be a problem related to AspectJ+Lombok+ECJ issues that you find a lot when you google for it, though that would normally show up as some exception during runtime.

I think you might have more luck to use lombok as a compiler plugin to modify your classes before any runtime magic occurs by spring-boot-devtools or AspectJ-LWT. You could also try disabling the spring-boot-devtools restart mechanism with the jvm param -Dspring.devtools.restart.enabled=false (should also work as a system property, though using it in application.properties did not work for me).

**Comment by subes** [comment] 2021-10-04 17:02
I tinkered a bit further with it. In the current state somehow I can not get Lombok to work in any way. Even removing spring-boot-devtools dependency does not help. So dunno, maybe it works, just not for me anymore? Even when I use your unmodified sample lombok does not want to work for me when I remove spring-boot-devtools.

So maybe you should have a look if one of the workarounds mentioned above works for you. I can not test this anymore since lombok does not work at all for me right now.

**Comment by subes** [comment] 2021-10-04 17:15
Though I think with lombok aside:
- with a proper aop.xml that enables the mentioned aspects (spring-aspects.jar contains one such aop.xml) 
- and reweaving enabled with a custom aop.xml using -Xreweavable
- and the `org.aspectj.weaver.loadtime.Agent.agentmain("", InstrumentationSavingAgent.getInstrumentation());` workaround for spring-boot-devtools reloading of aspectj 

your initial problem with the @async @Cacheable should be resolved.

I have documented these workarounds here: https://github.com/invesdwin/invesdwin-instrument/blob/master/README.md#spring-boot-devtools

**Comment by subes** [comment] 2021-10-16 14:18
Closing, reopen if you encounter more issues.

**Closed as completed by subes** 2021-10-16 14:18 UTC
